
	 	/**
         IMPORTANT !!!

         DO NOT EDIT THIS FILE. IT IS GENERATED FROM approriate xml file in xmlresources/gbcommands BY
         THE JavaClassesGenerator.xslt. MODIFY THAT FILE INSTEAD OF THIS ONE.
         
         Use Ant task process-gb-messages after that to generate .java files again.
         
         IMPORTANT END !!!
        */
 	package cz.cuni.amis.pogamut.ut2004.communication.messages.gbcommands;import java.util.*;import javax.vecmath.*;import cz.cuni.amis.pogamut.base.communication.messages.*;import cz.cuni.amis.pogamut.base.communication.worldview.*;import cz.cuni.amis.pogamut.base.communication.worldview.event.*;import cz.cuni.amis.pogamut.base.communication.worldview.object.*;import cz.cuni.amis.pogamut.multi.communication.worldview.object.*;import cz.cuni.amis.pogamut.base.communication.translator.event.*;import cz.cuni.amis.pogamut.multi.communication.translator.event.*;import cz.cuni.amis.pogamut.base3d.worldview.object.*;import cz.cuni.amis.pogamut.base3d.worldview.object.event.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.*;import cz.cuni.amis.pogamut.ut2004.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004.communication.translator.itemdescriptor.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.ItemType.Category;import cz.cuni.amis.pogamut.unreal.communication.messages.UnrealId;import cz.cuni.amis.utils.exception.*;import cz.cuni.amis.pogamut.base.communication.translator.event.IWorldObjectUpdateResult.Result;import cz.cuni.amis.utils.SafeEquals;import cz.cuni.amis.pogamut.base.agent.*;import cz.cuni.amis.pogamut.multi.agent.*;import cz.cuni.amis.pogamut.multi.communication.worldview.property.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.property.*;import cz.cuni.amis.utils.token.*;import cz.cuni.amis.utils.*;
 		/**
 		 * Representation of the GameBots2004 command COMBO.
 		 *
 		 * 
		Causes bot to perform desired adrenaline combo (only if it has enough adrenaline usually >= 100). Combo cannot be turned off when triggered. 
     Combo will consume bot adrenaline slowly, when it reaches 0 combo stops. Combo can modify bots abilities or appearance. Combos can be xGame.ComboBerserk (bigger damage), xGame.ComboDefensive (every few seconds adds health), xGame.ComboInvis (bot is invisible and is very hard to spot) or xGame.ComboSpeed (bots speed is increased).
	
         */
 	public class Combo 
		extends CommandMessage
	        {
	        	
		        
    	/** Example how the message looks like - used during parser tests. */
    	public static final String PROTOTYPE =
    		" {Type text} ";
    
		/**
		 * Creates new instance of command Combo.
		 * 
		Causes bot to perform desired adrenaline combo (only if it has enough adrenaline usually >= 100). Combo cannot be turned off when triggered. 
     Combo will consume bot adrenaline slowly, when it reaches 0 combo stops. Combo can modify bots abilities or appearance. Combos can be xGame.ComboBerserk (bigger damage), xGame.ComboDefensive (every few seconds adds health), xGame.ComboInvis (bot is invisible and is very hard to spot) or xGame.ComboSpeed (bots speed is increased).
	
		 * Corresponding GameBots message for this command is
		 * COMBO.
		 *
		 * 
		 *    @param Type 
			Holds the class name of the desired adrenaline combo (can be
			xGame.ComboBerserk, xGame.ComboDefensive, xGame.ComboInvis
			or xGame.ComboSpeed).
		
		 */
		public Combo(
			String Type
		) {
			
				this.Type = Type;
            
		}

		
			/**
			 * Creates new instance of command Combo.
			 * 
		Causes bot to perform desired adrenaline combo (only if it has enough adrenaline usually >= 100). Combo cannot be turned off when triggered. 
     Combo will consume bot adrenaline slowly, when it reaches 0 combo stops. Combo can modify bots abilities or appearance. Combos can be xGame.ComboBerserk (bigger damage), xGame.ComboDefensive (every few seconds adds health), xGame.ComboInvis (bot is invisible and is very hard to spot) or xGame.ComboSpeed (bots speed is increased).
	
			 * Corresponding GameBots message for this command is
			 * COMBO.
			 * <p></p>
			 * WARNING: this is empty-command constructor, you have to use setters to fill it up with data that should be sent to GameBots2004!
		     */
		    public Combo() {
		    }
			
		
		/**
		 * Cloning constructor.
		 *
		 * @param original
		 */
		public Combo(Combo original) {
		   
		        this.Type = original.Type;
		   
		}
    
	        /**
	        
			Holds the class name of the desired adrenaline combo (can be
			xGame.ComboBerserk, xGame.ComboDefensive, xGame.ComboInvis
			or xGame.ComboSpeed).
		 
	        */
	        protected
	         String Type =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * 
			Holds the class name of the desired adrenaline combo (can be
			xGame.ComboBerserk, xGame.ComboDefensive, xGame.ComboInvis
			or xGame.ComboSpeed).
		 
         */
        public String getType()
 	
	        {
	            return
	        	 Type;
	        }
	        
	        
	        
 		
 		/**
         * 
			Holds the class name of the desired adrenaline combo (can be
			xGame.ComboBerserk, xGame.ComboDefensive, xGame.ComboInvis
			or xGame.ComboSpeed).
		 
         */
        public Combo 
        setType(String Type)
 	
			{
				this.Type = Type;
				return this;
			}
		
 	    public String toString() {
            return toMessage();
        }
 	
 		public String toHtmlString() {
			return super.toString() + "[<br/>" +
            	
            	"<b>Type</b> = " +
            	String.valueOf(getType()
 	) +
            	" <br/> " +
            	 
            	"<br/>]"
            ;
		}
 	
		public String toMessage() {
     		StringBuffer buf = new StringBuffer();
     		buf.append("COMBO");
     		
						if (Type != null) {
							buf.append(" {Type " + Type + "}");
						}
					
   			return buf.toString();
   		}
 	
 		// --- Extra Java from XML BEGIN (extra/code/java)
        	
		// --- Extra Java from XML END (extra/code/java)
 	
	        }
    	