
	 	/**
         IMPORTANT !!!

         DO NOT EDIT THIS FILE. IT IS GENERATED FROM approriate xml file in xmlresources/gbcommands BY
         THE JavaClassesGenerator.xslt. MODIFY THAT FILE INSTEAD OF THIS ONE.
         
         Use Ant task process-gb-messages after that to generate .java files again.
         
         IMPORTANT END !!!
        */
 	package cz.cuni.amis.pogamut.ut2004.communication.messages.gbcommands;import java.util.*;import javax.vecmath.*;import cz.cuni.amis.pogamut.base.communication.messages.*;import cz.cuni.amis.pogamut.base.communication.worldview.*;import cz.cuni.amis.pogamut.base.communication.worldview.event.*;import cz.cuni.amis.pogamut.base.communication.worldview.object.*;import cz.cuni.amis.pogamut.multi.communication.worldview.object.*;import cz.cuni.amis.pogamut.base.communication.translator.event.*;import cz.cuni.amis.pogamut.multi.communication.translator.event.*;import cz.cuni.amis.pogamut.base3d.worldview.object.*;import cz.cuni.amis.pogamut.base3d.worldview.object.event.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.*;import cz.cuni.amis.pogamut.ut2004.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004.communication.translator.itemdescriptor.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.ItemType.Category;import cz.cuni.amis.pogamut.unreal.communication.messages.UnrealId;import cz.cuni.amis.utils.exception.*;import cz.cuni.amis.pogamut.base.communication.translator.event.IWorldObjectUpdateResult.Result;import cz.cuni.amis.utils.SafeEquals;import cz.cuni.amis.pogamut.base.agent.*;import cz.cuni.amis.pogamut.multi.agent.*;import cz.cuni.amis.pogamut.multi.communication.worldview.property.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.property.*;import cz.cuni.amis.utils.token.*;import cz.cuni.amis.utils.*;
 		/**
 		 * Representation of the GameBots2004 command ENTER.
 		 *
 		 * 
		Tries to enter vehicle specified by Id. Note:
		You have to be in vehicle EntryRadius to enter (default 100 ut units). 
		Response to this command are messages ENTERED and LOCKED.
		Beware! When in vehicle just command RUNTO with Target specified works for move commands. Any other move commands will cause vehicle to got straight ahead.
	Also it is not possible to control speed or steering at this moment. Everything is done automaticaly by RUNTO with Target specified.
	
         */
 	public class EnterVehicle 
		extends CommandMessage
	        {
	        	
		        
    	/** Example how the message looks like - used during parser tests. */
    	public static final String PROTOTYPE =
    		" {Id unreal_id} ";
    
		/**
		 * Creates new instance of command EnterVehicle.
		 * 
		Tries to enter vehicle specified by Id. Note:
		You have to be in vehicle EntryRadius to enter (default 100 ut units). 
		Response to this command are messages ENTERED and LOCKED.
		Beware! When in vehicle just command RUNTO with Target specified works for move commands. Any other move commands will cause vehicle to got straight ahead.
	Also it is not possible to control speed or steering at this moment. Everything is done automaticaly by RUNTO with Target specified.
	
		 * Corresponding GameBots message for this command is
		 * ENTER.
		 *
		 * 
		 *    @param Id Id of the vehicle we want to enter.
		 */
		public EnterVehicle(
			UnrealId Id
		) {
			
				this.Id = Id;
            
		}

		
			/**
			 * Creates new instance of command EnterVehicle.
			 * 
		Tries to enter vehicle specified by Id. Note:
		You have to be in vehicle EntryRadius to enter (default 100 ut units). 
		Response to this command are messages ENTERED and LOCKED.
		Beware! When in vehicle just command RUNTO with Target specified works for move commands. Any other move commands will cause vehicle to got straight ahead.
	Also it is not possible to control speed or steering at this moment. Everything is done automaticaly by RUNTO with Target specified.
	
			 * Corresponding GameBots message for this command is
			 * ENTER.
			 * <p></p>
			 * WARNING: this is empty-command constructor, you have to use setters to fill it up with data that should be sent to GameBots2004!
		     */
		    public EnterVehicle() {
		    }
			
		
		/**
		 * Cloning constructor.
		 *
		 * @param original
		 */
		public EnterVehicle(EnterVehicle original) {
		   
		        this.Id = original.Id;
		   
		}
    
	        /**
	        Id of the vehicle we want to enter. 
	        */
	        protected
	         UnrealId Id =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * Id of the vehicle we want to enter. 
         */
        public UnrealId getId()
 	
	        {
	            return
	        	 Id;
	        }
	        
	        
	        
 		
 		/**
         * Id of the vehicle we want to enter. 
         */
        public EnterVehicle 
        setId(UnrealId Id)
 	
			{
				this.Id = Id;
				return this;
			}
		
 	    public String toString() {
            return toMessage();
        }
 	
 		public String toHtmlString() {
			return super.toString() + "[<br/>" +
            	
            	"<b>Id</b> = " +
            	String.valueOf(getId()
 	) +
            	" <br/> " +
            	 
            	"<br/>]"
            ;
		}
 	
		public String toMessage() {
     		StringBuffer buf = new StringBuffer();
     		buf.append("ENTER");
     		
						if (Id != null) {
							buf.append(" {Id " + Id.getStringId() + "}");
						}
					
   			return buf.toString();
   		}
 	
 		// --- Extra Java from XML BEGIN (extra/code/java)
        	
		// --- Extra Java from XML END (extra/code/java)
 	
	        }
    	