
	 	/**
         IMPORTANT !!!

         DO NOT EDIT THIS FILE. IT IS GENERATED FROM approriate xml file in xmlresources/gbcommands BY
         THE JavaClassesGenerator.xslt. MODIFY THAT FILE INSTEAD OF THIS ONE.
         
         Use Ant task process-gb-messages after that to generate .java files again.
         
         IMPORTANT END !!!
        */
 	package cz.cuni.amis.pogamut.ut2004.communication.messages.gbcommands;import java.util.*;import javax.vecmath.*;import cz.cuni.amis.pogamut.base.communication.messages.*;import cz.cuni.amis.pogamut.base.communication.worldview.*;import cz.cuni.amis.pogamut.base.communication.worldview.event.*;import cz.cuni.amis.pogamut.base.communication.worldview.object.*;import cz.cuni.amis.pogamut.multi.communication.worldview.object.*;import cz.cuni.amis.pogamut.base.communication.translator.event.*;import cz.cuni.amis.pogamut.multi.communication.translator.event.*;import cz.cuni.amis.pogamut.base3d.worldview.object.*;import cz.cuni.amis.pogamut.base3d.worldview.object.event.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.*;import cz.cuni.amis.pogamut.ut2004.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004.communication.translator.itemdescriptor.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.ItemType.Category;import cz.cuni.amis.pogamut.unreal.communication.messages.UnrealId;import cz.cuni.amis.utils.exception.*;import cz.cuni.amis.pogamut.base.communication.translator.event.IWorldObjectUpdateResult.Result;import cz.cuni.amis.utils.SafeEquals;import cz.cuni.amis.pogamut.base.agent.*;import cz.cuni.amis.pogamut.multi.agent.*;import cz.cuni.amis.pogamut.multi.communication.worldview.property.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.property.*;import cz.cuni.amis.utils.token.*;import cz.cuni.amis.utils.*;
 		/**
 		 * Representation of the GameBots2004 command FTRACE.
 		 *
 		 * 
		Will send a ray from specified location to specified
		destination, responds with FTR message. FTRACE uses FastTrace
		function, which is faster then Trace function, but still rather
		slow.
	
         */
 	public class FastTrace 
		extends CommandMessage
	        {
	        	
		        
    	/** Example how the message looks like - used during parser tests. */
    	public static final String PROTOTYPE =
    		" {Id text}  {From 0,0,0}  {To 0,0,0} ";
    
		/**
		 * Creates new instance of command FastTrace.
		 * 
		Will send a ray from specified location to specified
		destination, responds with FTR message. FTRACE uses FastTrace
		function, which is faster then Trace function, but still rather
		slow.
	
		 * Corresponding GameBots message for this command is
		 * FTRACE.
		 *
		 * 
		 *    @param Id 
			Message Id made up by you and echoed in response so you can
			match up response with query.
		
		 *    @param From 
			Origin point of the ray. If you won't support From
			attribute, current bot location will be taken as From.
		
		 *    @param To Target point of the ray.
		 */
		public FastTrace(
			String Id,  Location From,  Location To
		) {
			
				this.Id = Id;
            
				this.From = From;
            
				this.To = To;
            
		}

		
			/**
			 * Creates new instance of command FastTrace.
			 * 
		Will send a ray from specified location to specified
		destination, responds with FTR message. FTRACE uses FastTrace
		function, which is faster then Trace function, but still rather
		slow.
	
			 * Corresponding GameBots message for this command is
			 * FTRACE.
			 * <p></p>
			 * WARNING: this is empty-command constructor, you have to use setters to fill it up with data that should be sent to GameBots2004!
		     */
		    public FastTrace() {
		    }
			
		
		/**
		 * Cloning constructor.
		 *
		 * @param original
		 */
		public FastTrace(FastTrace original) {
		   
		        this.Id = original.Id;
		   
		        this.From = original.From;
		   
		        this.To = original.To;
		   
		}
    
	        /**
	        
			Message Id made up by you and echoed in response so you can
			match up response with query.
		 
	        */
	        protected
	         String Id =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * 
			Message Id made up by you and echoed in response so you can
			match up response with query.
		 
         */
        public String getId()
 	
	        {
	            return
	        	 Id;
	        }
	        
	        
	        
 		
 		/**
         * 
			Message Id made up by you and echoed in response so you can
			match up response with query.
		 
         */
        public FastTrace 
        setId(String Id)
 	
			{
				this.Id = Id;
				return this;
			}
		
	        /**
	        
			Origin point of the ray. If you won't support From
			attribute, current bot location will be taken as From.
		 
	        */
	        protected
	         Location From =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * 
			Origin point of the ray. If you won't support From
			attribute, current bot location will be taken as From.
		 
         */
        public Location getFrom()
 	
	        {
	            return
	        	 From;
	        }
	        
	        
	        
 		
 		/**
         * 
			Origin point of the ray. If you won't support From
			attribute, current bot location will be taken as From.
		 
         */
        public FastTrace 
        setFrom(Location From)
 	
			{
				this.From = From;
				return this;
			}
		
	        /**
	        Target point of the ray. 
	        */
	        protected
	         Location To =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * Target point of the ray. 
         */
        public Location getTo()
 	
	        {
	            return
	        	 To;
	        }
	        
	        
	        
 		
 		/**
         * Target point of the ray. 
         */
        public FastTrace 
        setTo(Location To)
 	
			{
				this.To = To;
				return this;
			}
		
 	    public String toString() {
            return toMessage();
        }
 	
 		public String toHtmlString() {
			return super.toString() + "[<br/>" +
            	
            	"<b>Id</b> = " +
            	String.valueOf(getId()
 	) +
            	" <br/> " +
            	
            	"<b>From</b> = " +
            	String.valueOf(getFrom()
 	) +
            	" <br/> " +
            	
            	"<b>To</b> = " +
            	String.valueOf(getTo()
 	) +
            	" <br/> " +
            	 
            	"<br/>]"
            ;
		}
 	
		public String toMessage() {
     		StringBuffer buf = new StringBuffer();
     		buf.append("FTRACE");
     		
						if (Id != null) {
							buf.append(" {Id " + Id + "}");
						}
					
					    if (From != null) {
					        buf.append(" {From " +
					            From.getX() + "," +
					            From.getY() + "," +
					            From.getZ() + "}");
					    }
					
					    if (To != null) {
					        buf.append(" {To " +
					            To.getX() + "," +
					            To.getY() + "," +
					            To.getZ() + "}");
					    }
					
   			return buf.toString();
   		}
 	
 		// --- Extra Java from XML BEGIN (extra/code/java)
        	
		// --- Extra Java from XML END (extra/code/java)
 	
	        }
    	