
	 	/**
         IMPORTANT !!!

         DO NOT EDIT THIS FILE. IT IS GENERATED FROM approriate xml file in xmlresources/gbcommands BY
         THE JavaClassesGenerator.xslt. MODIFY THAT FILE INSTEAD OF THIS ONE.
         
         Use Ant task process-gb-messages after that to generate .java files again.
         
         IMPORTANT END !!!
        */
 	package cz.cuni.amis.pogamut.ut2004.communication.messages.gbcommands;import java.util.*;import javax.vecmath.*;import cz.cuni.amis.pogamut.base.communication.messages.*;import cz.cuni.amis.pogamut.base.communication.worldview.*;import cz.cuni.amis.pogamut.base.communication.worldview.event.*;import cz.cuni.amis.pogamut.base.communication.worldview.object.*;import cz.cuni.amis.pogamut.multi.communication.worldview.object.*;import cz.cuni.amis.pogamut.base.communication.translator.event.*;import cz.cuni.amis.pogamut.multi.communication.translator.event.*;import cz.cuni.amis.pogamut.base3d.worldview.object.*;import cz.cuni.amis.pogamut.base3d.worldview.object.event.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.*;import cz.cuni.amis.pogamut.ut2004.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004.communication.translator.itemdescriptor.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.ItemType.Category;import cz.cuni.amis.pogamut.unreal.communication.messages.UnrealId;import cz.cuni.amis.utils.exception.*;import cz.cuni.amis.pogamut.base.communication.translator.event.IWorldObjectUpdateResult.Result;import cz.cuni.amis.utils.SafeEquals;import cz.cuni.amis.pogamut.base.agent.*;import cz.cuni.amis.pogamut.multi.agent.*;import cz.cuni.amis.pogamut.multi.communication.worldview.property.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.property.*;import cz.cuni.amis.utils.token.*;import cz.cuni.amis.utils.*;
 		/**
 		 * Representation of the GameBots2004 command SETDEBUG.
 		 *
 		 * 
		Sets the debug information for current bot - displayable on HUD.
	
         */
 	public class SetBotDebug 
		extends CommandMessage
	        {
	        	
		        
    	/** Example how the message looks like - used during parser tests. */
    	public static final String PROTOTYPE =
    		" {Clear False}  {BehName text}  {StateName text}  {FocName text} ";
    
		/**
		 * Creates new instance of command SetBotDebug.
		 * 
		Sets the debug information for current bot - displayable on HUD.
	
		 * Corresponding GameBots message for this command is
		 * SETDEBUG.
		 *
		 * 
		 *    @param Clear 
            If true then erases previously sent debug info.
        
		 *    @param BehName 
            Name of currently active behavior.
        
		 *    @param StateName 
            Name of currently active behavior state.
        
		 *    @param FocName 
            Name of current bot behavior focus - other character.
        
		 */
		public SetBotDebug(
			Boolean Clear,  String BehName,  String StateName,  String FocName
		) {
			
				this.Clear = Clear;
            
				this.BehName = BehName;
            
				this.StateName = StateName;
            
				this.FocName = FocName;
            
		}

		
			/**
			 * Creates new instance of command SetBotDebug.
			 * 
		Sets the debug information for current bot - displayable on HUD.
	
			 * Corresponding GameBots message for this command is
			 * SETDEBUG.
			 * <p></p>
			 * WARNING: this is empty-command constructor, you have to use setters to fill it up with data that should be sent to GameBots2004!
		     */
		    public SetBotDebug() {
		    }
			
		
		/**
		 * Cloning constructor.
		 *
		 * @param original
		 */
		public SetBotDebug(SetBotDebug original) {
		   
		        this.Clear = original.Clear;
		   
		        this.BehName = original.BehName;
		   
		        this.StateName = original.StateName;
		   
		        this.FocName = original.FocName;
		   
		}
    
	        /**
	        
            If true then erases previously sent debug info.
         
	        */
	        protected
	         Boolean Clear =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * 
            If true then erases previously sent debug info.
         
         */
        public Boolean isClear()
 	
	        {
	            return
	        	 Clear;
	        }
	        
	        
	        
 		
 		/**
         * 
            If true then erases previously sent debug info.
         
         */
        public SetBotDebug 
        setClear(Boolean Clear)
 	
			{
				this.Clear = Clear;
				return this;
			}
		
	        /**
	        
            Name of currently active behavior.
         
	        */
	        protected
	         String BehName =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * 
            Name of currently active behavior.
         
         */
        public String getBehName()
 	
	        {
	            return
	        	 BehName;
	        }
	        
	        
	        
 		
 		/**
         * 
            Name of currently active behavior.
         
         */
        public SetBotDebug 
        setBehName(String BehName)
 	
			{
				this.BehName = BehName;
				return this;
			}
		
	        /**
	        
            Name of currently active behavior state.
         
	        */
	        protected
	         String StateName =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * 
            Name of currently active behavior state.
         
         */
        public String getStateName()
 	
	        {
	            return
	        	 StateName;
	        }
	        
	        
	        
 		
 		/**
         * 
            Name of currently active behavior state.
         
         */
        public SetBotDebug 
        setStateName(String StateName)
 	
			{
				this.StateName = StateName;
				return this;
			}
		
	        /**
	        
            Name of current bot behavior focus - other character.
         
	        */
	        protected
	         String FocName =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * 
            Name of current bot behavior focus - other character.
         
         */
        public String getFocName()
 	
	        {
	            return
	        	 FocName;
	        }
	        
	        
	        
 		
 		/**
         * 
            Name of current bot behavior focus - other character.
         
         */
        public SetBotDebug 
        setFocName(String FocName)
 	
			{
				this.FocName = FocName;
				return this;
			}
		
 	    public String toString() {
            return toMessage();
        }
 	
 		public String toHtmlString() {
			return super.toString() + "[<br/>" +
            	
            	"<b>Clear</b> = " +
            	String.valueOf(isClear()
 	) +
            	" <br/> " +
            	
            	"<b>BehName</b> = " +
            	String.valueOf(getBehName()
 	) +
            	" <br/> " +
            	
            	"<b>StateName</b> = " +
            	String.valueOf(getStateName()
 	) +
            	" <br/> " +
            	
            	"<b>FocName</b> = " +
            	String.valueOf(getFocName()
 	) +
            	" <br/> " +
            	 
            	"<br/>]"
            ;
		}
 	
		public String toMessage() {
     		StringBuffer buf = new StringBuffer();
     		buf.append("SETDEBUG");
     		
						if (Clear != null) {
							buf.append(" {Clear " + Clear + "}");
						}
					
						if (BehName != null) {
							buf.append(" {BehName " + BehName + "}");
						}
					
						if (StateName != null) {
							buf.append(" {StateName " + StateName + "}");
						}
					
						if (FocName != null) {
							buf.append(" {FocName " + FocName + "}");
						}
					
   			return buf.toString();
   		}
 	
 		// --- Extra Java from XML BEGIN (extra/code/java)
        	
		// --- Extra Java from XML END (extra/code/java)
 	
	        }
    	