
	 	/**
         IMPORTANT !!!

         DO NOT EDIT THIS FILE. IT IS GENERATED FROM approriate xml file in xmlresources/gbcommands BY
         THE JavaClassesGenerator.xslt. MODIFY THAT FILE INSTEAD OF THIS ONE.
         
         Use Ant task process-gb-messages after that to generate .java files again.
         
         IMPORTANT END !!!
        */
 	package cz.cuni.amis.pogamut.ut2004.communication.messages.gbcommands;import java.util.*;import javax.vecmath.*;import cz.cuni.amis.pogamut.base.communication.messages.*;import cz.cuni.amis.pogamut.base.communication.worldview.*;import cz.cuni.amis.pogamut.base.communication.worldview.event.*;import cz.cuni.amis.pogamut.base.communication.worldview.object.*;import cz.cuni.amis.pogamut.multi.communication.worldview.object.*;import cz.cuni.amis.pogamut.base.communication.translator.event.*;import cz.cuni.amis.pogamut.multi.communication.translator.event.*;import cz.cuni.amis.pogamut.base3d.worldview.object.*;import cz.cuni.amis.pogamut.base3d.worldview.object.event.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.*;import cz.cuni.amis.pogamut.ut2004.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004.communication.translator.itemdescriptor.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.ItemType.Category;import cz.cuni.amis.pogamut.unreal.communication.messages.UnrealId;import cz.cuni.amis.utils.exception.*;import cz.cuni.amis.pogamut.base.communication.translator.event.IWorldObjectUpdateResult.Result;import cz.cuni.amis.utils.SafeEquals;import cz.cuni.amis.pogamut.base.agent.*;import cz.cuni.amis.pogamut.multi.agent.*;import cz.cuni.amis.pogamut.multi.communication.worldview.property.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.property.*;import cz.cuni.amis.utils.token.*;import cz.cuni.amis.utils.*;
 		/**
 		 * Representation of the GameBots2004 command SETCROUCH.
 		 *
 		 * 
		Will crouch/uncrouch the bot. If crouched you cannot jump. If
		killed, this will be reset.
	
         */
 	public class SetCrouch 
		extends CommandMessage
	        {
	        	
		        
    	/** Example how the message looks like - used during parser tests. */
    	public static final String PROTOTYPE =
    		" {Crouch False} ";
    
		/**
		 * Creates new instance of command SetCrouch.
		 * 
		Will crouch/uncrouch the bot. If crouched you cannot jump. If
		killed, this will be reset.
	
		 * Corresponding GameBots message for this command is
		 * SETCROUCH.
		 *
		 * 
		 *    @param Crouch 
			True or false to crouch or unrouch.
		
		 */
		public SetCrouch(
			Boolean Crouch
		) {
			
				this.Crouch = Crouch;
            
		}

		
			/**
			 * Creates new instance of command SetCrouch.
			 * 
		Will crouch/uncrouch the bot. If crouched you cannot jump. If
		killed, this will be reset.
	
			 * Corresponding GameBots message for this command is
			 * SETCROUCH.
			 * <p></p>
			 * WARNING: this is empty-command constructor, you have to use setters to fill it up with data that should be sent to GameBots2004!
		     */
		    public SetCrouch() {
		    }
			
		
		/**
		 * Cloning constructor.
		 *
		 * @param original
		 */
		public SetCrouch(SetCrouch original) {
		   
		        this.Crouch = original.Crouch;
		   
		}
    
	        /**
	        
			True or false to crouch or unrouch.
		 
	        */
	        protected
	         Boolean Crouch =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * 
			True or false to crouch or unrouch.
		 
         */
        public Boolean isCrouch()
 	
	        {
	            return
	        	 Crouch;
	        }
	        
	        
	        
 		
 		/**
         * 
			True or false to crouch or unrouch.
		 
         */
        public SetCrouch 
        setCrouch(Boolean Crouch)
 	
			{
				this.Crouch = Crouch;
				return this;
			}
		
 	    public String toString() {
            return toMessage();
        }
 	
 		public String toHtmlString() {
			return super.toString() + "[<br/>" +
            	
            	"<b>Crouch</b> = " +
            	String.valueOf(isCrouch()
 	) +
            	" <br/> " +
            	 
            	"<br/>]"
            ;
		}
 	
		public String toMessage() {
     		StringBuffer buf = new StringBuffer();
     		buf.append("SETCROUCH");
     		
						if (Crouch != null) {
							buf.append(" {Crouch " + Crouch + "}");
						}
					
   			return buf.toString();
   		}
 	
 		// --- Extra Java from XML BEGIN (extra/code/java)
        	
		// --- Extra Java from XML END (extra/code/java)
 	
	        }
    	