
	 	/**
         IMPORTANT !!!

         DO NOT EDIT THIS FILE. IT IS GENERATED FROM approriate xml file in xmlresources/gbcommands BY
         THE JavaClassesGenerator.xslt. MODIFY THAT FILE INSTEAD OF THIS ONE.
         
         Use Ant task process-gb-messages after that to generate .java files again.
         
         IMPORTANT END !!!
        */
 	package cz.cuni.amis.pogamut.ut2004.communication.messages.gbcommands;import java.util.*;import javax.vecmath.*;import cz.cuni.amis.pogamut.base.communication.messages.*;import cz.cuni.amis.pogamut.base.communication.worldview.*;import cz.cuni.amis.pogamut.base.communication.worldview.event.*;import cz.cuni.amis.pogamut.base.communication.worldview.object.*;import cz.cuni.amis.pogamut.multi.communication.worldview.object.*;import cz.cuni.amis.pogamut.base.communication.translator.event.*;import cz.cuni.amis.pogamut.multi.communication.translator.event.*;import cz.cuni.amis.pogamut.base3d.worldview.object.*;import cz.cuni.amis.pogamut.base3d.worldview.object.event.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.*;import cz.cuni.amis.pogamut.ut2004.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004.communication.translator.itemdescriptor.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.ItemType.Category;import cz.cuni.amis.pogamut.unreal.communication.messages.UnrealId;import cz.cuni.amis.utils.exception.*;import cz.cuni.amis.pogamut.base.communication.translator.event.IWorldObjectUpdateResult.Result;import cz.cuni.amis.utils.SafeEquals;import cz.cuni.amis.pogamut.base.agent.*;import cz.cuni.amis.pogamut.multi.agent.*;import cz.cuni.amis.pogamut.multi.communication.worldview.property.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.property.*;import cz.cuni.amis.utils.token.*;import cz.cuni.amis.utils.*;
 		/**
 		 * Representation of the GameBots2004 command FORCECAM.
 		 *
 		 * 
		Sets input player to be a camera (he want be able to control himself). This player/camera can be controlled
		by MoveCamera command. Also sets camera location and rotation.
	
         */
 	public class SetCamera 
		extends CommandMessage
	        {
	        	
		        
    	/** Example how the message looks like - used during parser tests. */
    	public static final String PROTOTYPE =
    		" {Id unreal_id}  {Location 0,0,0}  {Rotation 0,0,0}  {Release False} ";
    
		/**
		 * Creates new instance of command SetCamera.
		 * 
		Sets input player to be a camera (he want be able to control himself). This player/camera can be controlled
		by MoveCamera command. Also sets camera location and rotation.
	
		 * Corresponding GameBots message for this command is
		 * FORCECAM.
		 *
		 * 
		 *    @param Id UnrealId of the player we want to set as a camera. 
		 *    @param Location Initial location of this camera. 
		 *    @param Rotation Initial rotation of this camera. 
		 *    @param Release True to release this player from camera mode. 
		 */
		public SetCamera(
			UnrealId Id,  Location Location,  Rotation Rotation,  Boolean Release
		) {
			
				this.Id = Id;
            
				this.Location = Location;
            
				this.Rotation = Rotation;
            
				this.Release = Release;
            
		}

		
			/**
			 * Creates new instance of command SetCamera.
			 * 
		Sets input player to be a camera (he want be able to control himself). This player/camera can be controlled
		by MoveCamera command. Also sets camera location and rotation.
	
			 * Corresponding GameBots message for this command is
			 * FORCECAM.
			 * <p></p>
			 * WARNING: this is empty-command constructor, you have to use setters to fill it up with data that should be sent to GameBots2004!
		     */
		    public SetCamera() {
		    }
			
		
		/**
		 * Cloning constructor.
		 *
		 * @param original
		 */
		public SetCamera(SetCamera original) {
		   
		        this.Id = original.Id;
		   
		        this.Location = original.Location;
		   
		        this.Rotation = original.Rotation;
		   
		        this.Release = original.Release;
		   
		}
    
	        /**
	        UnrealId of the player we want to set as a camera.  
	        */
	        protected
	         UnrealId Id =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * UnrealId of the player we want to set as a camera.  
         */
        public UnrealId getId()
 	
	        {
	            return
	        	 Id;
	        }
	        
	        
	        
 		
 		/**
         * UnrealId of the player we want to set as a camera.  
         */
        public SetCamera 
        setId(UnrealId Id)
 	
			{
				this.Id = Id;
				return this;
			}
		
	        /**
	        Initial location of this camera.  
	        */
	        protected
	         Location Location =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * Initial location of this camera.  
         */
        public Location getLocation()
 	
	        {
	            return
	        	 Location;
	        }
	        
	        
	        
 		
 		/**
         * Initial location of this camera.  
         */
        public SetCamera 
        setLocation(Location Location)
 	
			{
				this.Location = Location;
				return this;
			}
		
	        /**
	        Initial rotation of this camera.  
	        */
	        protected
	         Rotation Rotation =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * Initial rotation of this camera.  
         */
        public Rotation getRotation()
 	
	        {
	            return
	        	 Rotation;
	        }
	        
	        
	        
 		
 		/**
         * Initial rotation of this camera.  
         */
        public SetCamera 
        setRotation(Rotation Rotation)
 	
			{
				this.Rotation = Rotation;
				return this;
			}
		
	        /**
	        True to release this player from camera mode.  
	        */
	        protected
	         Boolean Release =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * True to release this player from camera mode.  
         */
        public Boolean isRelease()
 	
	        {
	            return
	        	 Release;
	        }
	        
	        
	        
 		
 		/**
         * True to release this player from camera mode.  
         */
        public SetCamera 
        setRelease(Boolean Release)
 	
			{
				this.Release = Release;
				return this;
			}
		
 	    public String toString() {
            return toMessage();
        }
 	
 		public String toHtmlString() {
			return super.toString() + "[<br/>" +
            	
            	"<b>Id</b> = " +
            	String.valueOf(getId()
 	) +
            	" <br/> " +
            	
            	"<b>Location</b> = " +
            	String.valueOf(getLocation()
 	) +
            	" <br/> " +
            	
            	"<b>Rotation</b> = " +
            	String.valueOf(getRotation()
 	) +
            	" <br/> " +
            	
            	"<b>Release</b> = " +
            	String.valueOf(isRelease()
 	) +
            	" <br/> " +
            	 
            	"<br/>]"
            ;
		}
 	
		public String toMessage() {
     		StringBuffer buf = new StringBuffer();
     		buf.append("FORCECAM");
     		
						if (Id != null) {
							buf.append(" {Id " + Id.getStringId() + "}");
						}
					
					    if (Location != null) {
					        buf.append(" {Location " +
					            Location.getX() + "," +
					            Location.getY() + "," +
					            Location.getZ() + "}");
					    }
					
					    if (Rotation != null) {
					        buf.append(" {Rotation " +
					            Rotation.getPitch() + "," +
					            Rotation.getYaw() + "," +
					            Rotation.getRoll() + "}");
					    }
					
						if (Release != null) {
							buf.append(" {Release " + Release + "}");
						}
					
   			return buf.toString();
   		}
 	
 		// --- Extra Java from XML BEGIN (extra/code/java)
        	
		// --- Extra Java from XML END (extra/code/java)
 	
	        }
    	