
	 	/**
         IMPORTANT !!!

         DO NOT EDIT THIS FILE. IT IS GENERATED FROM approriate xml file in xmlresources/gbcommands BY
         THE JavaClassesGenerator.xslt. MODIFY THAT FILE INSTEAD OF THIS ONE.
         
         Use Ant task process-gb-messages after that to generate .java files again.
         
         IMPORTANT END !!!
        */
 	package cz.cuni.amis.pogamut.ut2004.communication.messages.gbcommands;import java.util.*;import javax.vecmath.*;import cz.cuni.amis.pogamut.base.communication.messages.*;import cz.cuni.amis.pogamut.base.communication.worldview.*;import cz.cuni.amis.pogamut.base.communication.worldview.event.*;import cz.cuni.amis.pogamut.base.communication.worldview.object.*;import cz.cuni.amis.pogamut.multi.communication.worldview.object.*;import cz.cuni.amis.pogamut.base.communication.translator.event.*;import cz.cuni.amis.pogamut.multi.communication.translator.event.*;import cz.cuni.amis.pogamut.base3d.worldview.object.*;import cz.cuni.amis.pogamut.base3d.worldview.object.event.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.*;import cz.cuni.amis.pogamut.ut2004.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004.communication.translator.itemdescriptor.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.ItemType.Category;import cz.cuni.amis.pogamut.unreal.communication.messages.UnrealId;import cz.cuni.amis.utils.exception.*;import cz.cuni.amis.pogamut.base.communication.translator.event.IWorldObjectUpdateResult.Result;import cz.cuni.amis.utils.SafeEquals;import cz.cuni.amis.pogamut.base.agent.*;import cz.cuni.amis.pogamut.multi.agent.*;import cz.cuni.amis.pogamut.multi.communication.worldview.property.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.property.*;import cz.cuni.amis.utils.token.*;import cz.cuni.amis.utils.*;
 		/**
 		 * Representation of the GameBots2004 command SETLOCK.
 		 *
 		 * 
		Will disable new connections to bot server and or control server
		- depends on parameters. If last ControlServer instance is
		leaving. ControlServer lock will be canceled.
	
         */
 	public class SetLock 
		extends CommandMessage
	        {
	        	
		        
    	/** Example how the message looks like - used during parser tests. */
    	public static final String PROTOTYPE =
    		" {BotServer False}  {ControlServer False} ";
    
		/**
		 * Creates new instance of command SetLock.
		 * 
		Will disable new connections to bot server and or control server
		- depends on parameters. If last ControlServer instance is
		leaving. ControlServer lock will be canceled.
	
		 * Corresponding GameBots message for this command is
		 * SETLOCK.
		 *
		 * 
		 *    @param BotServer 
			If BotConnections should be locked.
		
		 *    @param ControlServer 
			If ControlConnections (server connections) should be locked.
		
		 */
		public SetLock(
			Boolean BotServer,  Boolean ControlServer
		) {
			
				this.BotServer = BotServer;
            
				this.ControlServer = ControlServer;
            
		}

		
			/**
			 * Creates new instance of command SetLock.
			 * 
		Will disable new connections to bot server and or control server
		- depends on parameters. If last ControlServer instance is
		leaving. ControlServer lock will be canceled.
	
			 * Corresponding GameBots message for this command is
			 * SETLOCK.
			 * <p></p>
			 * WARNING: this is empty-command constructor, you have to use setters to fill it up with data that should be sent to GameBots2004!
		     */
		    public SetLock() {
		    }
			
		
		/**
		 * Cloning constructor.
		 *
		 * @param original
		 */
		public SetLock(SetLock original) {
		   
		        this.BotServer = original.BotServer;
		   
		        this.ControlServer = original.ControlServer;
		   
		}
    
	        /**
	        
			If BotConnections should be locked.
		 
	        */
	        protected
	         Boolean BotServer =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * 
			If BotConnections should be locked.
		 
         */
        public Boolean isBotServer()
 	
	        {
	            return
	        	 BotServer;
	        }
	        
	        
	        
 		
 		/**
         * 
			If BotConnections should be locked.
		 
         */
        public SetLock 
        setBotServer(Boolean BotServer)
 	
			{
				this.BotServer = BotServer;
				return this;
			}
		
	        /**
	        
			If ControlConnections (server connections) should be locked.
		 
	        */
	        protected
	         Boolean ControlServer =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * 
			If ControlConnections (server connections) should be locked.
		 
         */
        public Boolean isControlServer()
 	
	        {
	            return
	        	 ControlServer;
	        }
	        
	        
	        
 		
 		/**
         * 
			If ControlConnections (server connections) should be locked.
		 
         */
        public SetLock 
        setControlServer(Boolean ControlServer)
 	
			{
				this.ControlServer = ControlServer;
				return this;
			}
		
 	    public String toString() {
            return toMessage();
        }
 	
 		public String toHtmlString() {
			return super.toString() + "[<br/>" +
            	
            	"<b>BotServer</b> = " +
            	String.valueOf(isBotServer()
 	) +
            	" <br/> " +
            	
            	"<b>ControlServer</b> = " +
            	String.valueOf(isControlServer()
 	) +
            	" <br/> " +
            	 
            	"<br/>]"
            ;
		}
 	
		public String toMessage() {
     		StringBuffer buf = new StringBuffer();
     		buf.append("SETLOCK");
     		
						if (BotServer != null) {
							buf.append(" {BotServer " + BotServer + "}");
						}
					
						if (ControlServer != null) {
							buf.append(" {ControlServer " + ControlServer + "}");
						}
					
   			return buf.toString();
   		}
 	
 		// --- Extra Java from XML BEGIN (extra/code/java)
        	
		// --- Extra Java from XML END (extra/code/java)
 	
	        }
    	