
	 	/**
         IMPORTANT !!!

         DO NOT EDIT THIS FILE. IT IS GENERATED FROM approriate xml file in xmlresources/gbcommands BY
         THE JavaClassesGenerator.xslt. MODIFY THAT FILE INSTEAD OF THIS ONE.
         
         Use Ant task process-gb-messages after that to generate .java files again.
         
         IMPORTANT END !!!
        */
 	package cz.cuni.amis.pogamut.ut2004.communication.messages.gbcommands;import java.util.*;import javax.vecmath.*;import cz.cuni.amis.pogamut.base.communication.messages.*;import cz.cuni.amis.pogamut.base.communication.worldview.*;import cz.cuni.amis.pogamut.base.communication.worldview.event.*;import cz.cuni.amis.pogamut.base.communication.worldview.object.*;import cz.cuni.amis.pogamut.multi.communication.worldview.object.*;import cz.cuni.amis.pogamut.base.communication.translator.event.*;import cz.cuni.amis.pogamut.multi.communication.translator.event.*;import cz.cuni.amis.pogamut.base3d.worldview.object.*;import cz.cuni.amis.pogamut.base3d.worldview.object.event.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.*;import cz.cuni.amis.pogamut.ut2004.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004.communication.translator.itemdescriptor.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.ItemType.Category;import cz.cuni.amis.pogamut.unreal.communication.messages.UnrealId;import cz.cuni.amis.utils.exception.*;import cz.cuni.amis.pogamut.base.communication.translator.event.IWorldObjectUpdateResult.Result;import cz.cuni.amis.utils.SafeEquals;import cz.cuni.amis.pogamut.base.agent.*;import cz.cuni.amis.pogamut.multi.agent.*;import cz.cuni.amis.pogamut.multi.communication.worldview.property.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.property.*;import cz.cuni.amis.utils.token.*;import cz.cuni.amis.utils.*;
 		/**
 		 * Representation of the GameBots2004 command SETPASS.
 		 *
 		 * 
		Sets the password for Bot and control connections. If the
		password is set the initiation of GB communication is changed to
		this: 1) A ---> GB sends HELLO message 2) B <--- user
		sends READY 3) C ... if the server is protected by pass: 3.a) C1
		---> GB sends PASSWORD {BlockedByIP="ip adress with port of
		the blocker (195.113.12.3:3001)"} 3.b) C2 <--- user sends
		password ( PASSWORD {Password pass}) ... if correct 3.c) C3
		---> GB sends PASSWDOK and info batch messages, user can
		continue normally .... if the password is wrong 3.d) C4 --->
		PASSWDWRONG and connection ends Note: If the user knows that
		server is passworded he can use PASSWORD {Password pass} command
		instead of READY, and will be checked and sent info batch
		messages immediately
	
         */
 	public class SetPassword 
		extends CommandMessage
	        {
	        	
		        
    	/** Example how the message looks like - used during parser tests. */
    	public static final String PROTOTYPE =
    		" {Password text} ";
    
		/**
		 * Creates new instance of command SetPassword.
		 * 
		Sets the password for Bot and control connections. If the
		password is set the initiation of GB communication is changed to
		this: 1) A ---> GB sends HELLO message 2) B <--- user
		sends READY 3) C ... if the server is protected by pass: 3.a) C1
		---> GB sends PASSWORD {BlockedByIP="ip adress with port of
		the blocker (195.113.12.3:3001)"} 3.b) C2 <--- user sends
		password ( PASSWORD {Password pass}) ... if correct 3.c) C3
		---> GB sends PASSWDOK and info batch messages, user can
		continue normally .... if the password is wrong 3.d) C4 --->
		PASSWDWRONG and connection ends Note: If the user knows that
		server is passworded he can use PASSWORD {Password pass} command
		instead of READY, and will be checked and sent info batch
		messages immediately
	
		 * Corresponding GameBots message for this command is
		 * SETPASS.
		 *
		 * 
		 *    @param Password Holds the password.
		 */
		public SetPassword(
			String Password
		) {
			
				this.Password = Password;
            
		}

		
			/**
			 * Creates new instance of command SetPassword.
			 * 
		Sets the password for Bot and control connections. If the
		password is set the initiation of GB communication is changed to
		this: 1) A ---> GB sends HELLO message 2) B <--- user
		sends READY 3) C ... if the server is protected by pass: 3.a) C1
		---> GB sends PASSWORD {BlockedByIP="ip adress with port of
		the blocker (195.113.12.3:3001)"} 3.b) C2 <--- user sends
		password ( PASSWORD {Password pass}) ... if correct 3.c) C3
		---> GB sends PASSWDOK and info batch messages, user can
		continue normally .... if the password is wrong 3.d) C4 --->
		PASSWDWRONG and connection ends Note: If the user knows that
		server is passworded he can use PASSWORD {Password pass} command
		instead of READY, and will be checked and sent info batch
		messages immediately
	
			 * Corresponding GameBots message for this command is
			 * SETPASS.
			 * <p></p>
			 * WARNING: this is empty-command constructor, you have to use setters to fill it up with data that should be sent to GameBots2004!
		     */
		    public SetPassword() {
		    }
			
		
		/**
		 * Cloning constructor.
		 *
		 * @param original
		 */
		public SetPassword(SetPassword original) {
		   
		        this.Password = original.Password;
		   
		}
    
	        /**
	        Holds the password. 
	        */
	        protected
	         String Password =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * Holds the password. 
         */
        public String getPassword()
 	
	        {
	            return
	        	 Password;
	        }
	        
	        
	        
 		
 		/**
         * Holds the password. 
         */
        public SetPassword 
        setPassword(String Password)
 	
			{
				this.Password = Password;
				return this;
			}
		
 	    public String toString() {
            return toMessage();
        }
 	
 		public String toHtmlString() {
			return super.toString() + "[<br/>" +
            	
            	"<b>Password</b> = " +
            	String.valueOf(getPassword()
 	) +
            	" <br/> " +
            	 
            	"<br/>]"
            ;
		}
 	
		public String toMessage() {
     		StringBuffer buf = new StringBuffer();
     		buf.append("SETPASS");
     		
						if (Password != null) {
							buf.append(" {Password " + Password + "}");
						}
					
   			return buf.toString();
   		}
 	
 		// --- Extra Java from XML BEGIN (extra/code/java)
        	
		// --- Extra Java from XML END (extra/code/java)
 	
	        }
    	