
	 	/**
         IMPORTANT !!!

         DO NOT EDIT THIS FILE. IT IS GENERATED FROM approriate xml file in xmlresources/gbcommands BY
         THE JavaClassesGenerator.xslt. MODIFY THAT FILE INSTEAD OF THIS ONE.
         
         Use Ant task process-gb-messages after that to generate .java files again.
         
         IMPORTANT END !!!
        */
 	package cz.cuni.amis.pogamut.ut2004.communication.messages.gbcommands;import java.util.*;import javax.vecmath.*;import cz.cuni.amis.pogamut.base.communication.messages.*;import cz.cuni.amis.pogamut.base.communication.worldview.*;import cz.cuni.amis.pogamut.base.communication.worldview.event.*;import cz.cuni.amis.pogamut.base.communication.worldview.object.*;import cz.cuni.amis.pogamut.multi.communication.worldview.object.*;import cz.cuni.amis.pogamut.base.communication.translator.event.*;import cz.cuni.amis.pogamut.multi.communication.translator.event.*;import cz.cuni.amis.pogamut.base3d.worldview.object.*;import cz.cuni.amis.pogamut.base3d.worldview.object.event.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.*;import cz.cuni.amis.pogamut.ut2004.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.objects.*;import cz.cuni.amis.pogamut.ut2004.communication.translator.itemdescriptor.*;import cz.cuni.amis.pogamut.ut2004.communication.messages.ItemType.Category;import cz.cuni.amis.pogamut.unreal.communication.messages.UnrealId;import cz.cuni.amis.utils.exception.*;import cz.cuni.amis.pogamut.base.communication.translator.event.IWorldObjectUpdateResult.Result;import cz.cuni.amis.utils.SafeEquals;import cz.cuni.amis.pogamut.base.agent.*;import cz.cuni.amis.pogamut.multi.agent.*;import cz.cuni.amis.pogamut.multi.communication.worldview.property.*;import cz.cuni.amis.pogamut.ut2004multi.communication.worldview.property.*;import cz.cuni.amis.utils.token.*;import cz.cuni.amis.utils.*;
 		/**
 		 * Representation of the GameBots2004 command TURNTO.
 		 *
 		 * 
		Specify a point, rotation value or object to turn towards.
	
         */
 	public class TurnTo 
		extends CommandMessage
	        {
	        	
		        
    	/** Example how the message looks like - used during parser tests. */
    	public static final String PROTOTYPE =
    		" {Target unreal_id}  {Rotation 0,0,0}  {Location 0,0,0} ";
    
		/**
		 * Creates new instance of command TurnTo.
		 * 
		Specify a point, rotation value or object to turn towards.
	
		 * Corresponding GameBots message for this command is
		 * TURNTO.
		 *
		 * 
		 *    @param Target 
			The unique id of a player/object/nav point/whatever that you
			want to face. Must be visible.
		
		 *    @param Rotation 
			Absolute rotation you want to spin to. Must be provided as comma
			delimited ("0,50000,0") and should be in absolute terms and
			in UT units (2pi = 65535 units). Used only if no target
			provided. Rotation is parsed: First pitch (up, down), then yaw (left, right), the roll (no effect here, however it is an equivalent of doing a cartwheel).
		
		 *    @param Location 
			Location you want to face. Normal rules for location. Only
			used if no Target or Rotation.
		
		 */
		public TurnTo(
			UnrealId Target,  Rotation Rotation,  Location Location
		) {
			
				this.Target = Target;
            
				this.Rotation = Rotation;
            
				this.Location = Location;
            
		}

		
			/**
			 * Creates new instance of command TurnTo.
			 * 
		Specify a point, rotation value or object to turn towards.
	
			 * Corresponding GameBots message for this command is
			 * TURNTO.
			 * <p></p>
			 * WARNING: this is empty-command constructor, you have to use setters to fill it up with data that should be sent to GameBots2004!
		     */
		    public TurnTo() {
		    }
			
		
		/**
		 * Cloning constructor.
		 *
		 * @param original
		 */
		public TurnTo(TurnTo original) {
		   
		        this.Target = original.Target;
		   
		        this.Rotation = original.Rotation;
		   
		        this.Location = original.Location;
		   
		}
    
	        /**
	        
			The unique id of a player/object/nav point/whatever that you
			want to face. Must be visible.
		 
	        */
	        protected
	         UnrealId Target =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * 
			The unique id of a player/object/nav point/whatever that you
			want to face. Must be visible.
		 
         */
        public UnrealId getTarget()
 	
	        {
	            return
	        	 Target;
	        }
	        
	        
	        
 		
 		/**
         * 
			The unique id of a player/object/nav point/whatever that you
			want to face. Must be visible.
		 
         */
        public TurnTo 
        setTarget(UnrealId Target)
 	
			{
				this.Target = Target;
				return this;
			}
		
	        /**
	        
			Absolute rotation you want to spin to. Must be provided as comma
			delimited ("0,50000,0") and should be in absolute terms and
			in UT units (2pi = 65535 units). Used only if no target
			provided. Rotation is parsed: First pitch (up, down), then yaw (left, right), the roll (no effect here, however it is an equivalent of doing a cartwheel).
		 
	        */
	        protected
	         Rotation Rotation =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * 
			Absolute rotation you want to spin to. Must be provided as comma
			delimited ("0,50000,0") and should be in absolute terms and
			in UT units (2pi = 65535 units). Used only if no target
			provided. Rotation is parsed: First pitch (up, down), then yaw (left, right), the roll (no effect here, however it is an equivalent of doing a cartwheel).
		 
         */
        public Rotation getRotation()
 	
	        {
	            return
	        	 Rotation;
	        }
	        
	        
	        
 		
 		/**
         * 
			Absolute rotation you want to spin to. Must be provided as comma
			delimited ("0,50000,0") and should be in absolute terms and
			in UT units (2pi = 65535 units). Used only if no target
			provided. Rotation is parsed: First pitch (up, down), then yaw (left, right), the roll (no effect here, however it is an equivalent of doing a cartwheel).
		 
         */
        public TurnTo 
        setRotation(Rotation Rotation)
 	
			{
				this.Rotation = Rotation;
				return this;
			}
		
	        /**
	        
			Location you want to face. Normal rules for location. Only
			used if no Target or Rotation.
		 
	        */
	        protected
	         Location Location =
	       	
	        		null
	        	;
	
	        
	        
 		/**
         * 
			Location you want to face. Normal rules for location. Only
			used if no Target or Rotation.
		 
         */
        public Location getLocation()
 	
	        {
	            return
	        	 Location;
	        }
	        
	        
	        
 		
 		/**
         * 
			Location you want to face. Normal rules for location. Only
			used if no Target or Rotation.
		 
         */
        public TurnTo 
        setLocation(Location Location)
 	
			{
				this.Location = Location;
				return this;
			}
		
 	    public String toString() {
            return toMessage();
        }
 	
 		public String toHtmlString() {
			return super.toString() + "[<br/>" +
            	
            	"<b>Target</b> = " +
            	String.valueOf(getTarget()
 	) +
            	" <br/> " +
            	
            	"<b>Rotation</b> = " +
            	String.valueOf(getRotation()
 	) +
            	" <br/> " +
            	
            	"<b>Location</b> = " +
            	String.valueOf(getLocation()
 	) +
            	" <br/> " +
            	 
            	"<br/>]"
            ;
		}
 	
		public String toMessage() {
     		StringBuffer buf = new StringBuffer();
     		buf.append("TURNTO");
     		
						if (Target != null) {
							buf.append(" {Target " + Target.getStringId() + "}");
						}
					
					    if (Rotation != null) {
					        buf.append(" {Rotation " +
					            Rotation.getPitch() + "," +
					            Rotation.getYaw() + "," +
					            Rotation.getRoll() + "}");
					    }
					
					    if (Location != null) {
					        buf.append(" {Location " +
					            Location.getX() + "," +
					            Location.getY() + "," +
					            Location.getZ() + "}");
					    }
					
   			return buf.toString();
   		}
 	
 		// --- Extra Java from XML BEGIN (extra/code/java)
        	
		// --- Extra Java from XML END (extra/code/java)
 	
	        }
    	